name: Github action test

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
  
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:

    - uses: actions/checkout@v3

    - name: setup python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Run update date
      working-directory: ./github_action
      run: python write_date.py
  
    - name: Auto commit date changes
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        commit_message: Update repo date
        branch: main
